//
//  LoginProtocols.swift
//  TwitterDM
//
//  Created Shashank Shandilya on 6/17/18.
//  Copyright © 2018 org. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LoginWireframeProtocol: class {
    func routeToDirectMessageListScene()
}

//MARK: Presenter -
protocol LoginPresenterProtocol: class {
    func userTappedOnLogin()
}

//MARK: Interactor -
protocol LoginInteractorProtocol: class {
    var presenter: LoginPresenterProtocol?  { get set }
    func logUserIntoTwitter(on success: @escaping ((_ userName: String) -> Void), on failure: @escaping ((_ error: Error) -> Void))
}

//MARK: View -
protocol LoginViewProtocol: class {
    var presenter: LoginPresenterProtocol?  { get set }
    func showLoader()
    func hideLoader()
    func showError(errorMessage: String)
}
