//
//  LoginPresenter.swift
//  TwitterDM
//
//  Created Shashank Shandilya on 6/17/18.
//  Copyright © 2018 org. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginPresenter: LoginPresenterProtocol {

    weak private var view: LoginViewProtocol?
    var interactor: LoginInteractorProtocol?
    private let router: LoginWireframeProtocol

    init(interface: LoginViewProtocol, interactor: LoginInteractorProtocol?, router: LoginWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func userTappedOnLogin() {
        view?.showLoader()
        interactor?.logUserIntoTwitter(on: { [weak self] (userName) in
            self?.view?.hideLoader()
            self?.router.routeToDirectMessageListScene()
        }, on: { [weak self] (error) in
            self?.view?.hideLoader()
            self?.view?.showError(errorMessage: error.localizedDescription)
        })
    }
}
