//
//  LoginInteractor.swift
//  TwitterDM
//
//  Created Shashank Shandilya on 6/17/18.
//  Copyright © 2018 org. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import TwitterKit

class LoginInteractor: LoginInteractorProtocol {
    weak var presenter: LoginPresenterProtocol?
    
    func logUserIntoTwitter(on success: @escaping ((String) -> Void), on failure: @escaping ((Error) -> Void)) {
        TWTRTwitter.sharedInstance().logIn(completion: { (session, error) in
            if session != nil {
                success(session!.userName)
            } else {
                failure(error!)
            }
        })
    }
}
