//
//  DirectMessageListRouter.swift
//  TwitterDM
//
//  Created Shashank Shandilya on 6/17/18.
//  Copyright © 2018 org. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DirectMessageListRouter: DirectMessageListWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = DirectMessageListViewController(nibName: nil, bundle: nil)
        let interactor = DirectMessageListInteractor()
        let router = DirectMessageListRouter()
        let presenter = DirectMessageListPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func routeToDetailScreen(withRecipientID recipientID: String, and events: [Event]) {
        viewController?.navigationController?.pushViewController(DirectMessageDetailRouter.createModule(with: recipientID, events: events), animated: true)
    }
}
