//
//  DirectMessageListViewController.swift
//  TwitterDM
//
//  Created Shashank Shandilya on 6/17/18.
//  Copyright © 2018 org. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DirectMessageListViewController: UIViewController, DirectMessageListViewProtocol {
    var presenter: DirectMessageListPresenterProtocol?
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    var recipients: [DirectMessageListViewModel.Recipients] = [] {
        didSet {
            tableView.reloadData()
        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.viewIsLoaded()
        let refreshControl = UIRefreshControl()
        refreshControl.addTarget(self, action: #selector(userRefreshed(_:)), for: UIControlEvents.valueChanged)
        tableView.refreshControl = refreshControl
    }
    
    @objc func userRefreshed(_ refreshControl: UIRefreshControl) {
        refreshControl.endRefreshing()
        presenter?.userRefreshedThePage()
    }
    
    func showLoader() {
        activityIndicator.startAnimating()
    }
    
    func hideLoader() {
        activityIndicator.stopAnimating()
    }
    
    func showError(errorMessage: String) {
        let alert = UIAlertController(title: nil, message: errorMessage, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
        navigationController?.present(alert, animated: true, completion: nil)
    }
}

extension DirectMessageListViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return recipients.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let model = recipients[indexPath.row]
        var cell = tableView.dequeueReusableCell(withIdentifier: "cell")
        if cell == nil {
            cell = UITableViewCell(style: .subtitle, reuseIdentifier: "cell")
        }
        
        cell!.textLabel?.text = model.recipientId
        cell!.detailTextLabel?.text = model.recentMessage?.text
        return cell!
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let model = recipients[indexPath.row]
        presenter?.userTapped(on: model)
    }
}
