//
//  DirectMessageListProtocols.swift
//  TwitterDM
//
//  Created Shashank Shandilya on 6/17/18.
//  Copyright © 2018 org. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DirectMessageListWireframeProtocol: class {
    func routeToDetailScreen(withRecipientID recipientID: String, and events: [Event])
}

//MARK: Presenter -
protocol DirectMessageListPresenterProtocol: class {
    func viewIsLoaded()
    func userTapped(on item: DirectMessageListViewModel.Recipients)
    func userRefreshedThePage()
}

//MARK: Interactor -
protocol DirectMessageListInteractorProtocol: class {
    var presenter: DirectMessageListPresenterProtocol?  { get set }
    func fetchDirectMessageList(_ success: @escaping (_ messageList: [[String: [Event]]]) -> Void, failure: @escaping (Error) -> Void)
    func events(for recipientID: String) -> [Event]
}

//MARK: View -
protocol DirectMessageListViewProtocol: class {
    var presenter: DirectMessageListPresenterProtocol?  { get set }
    var recipients: [DirectMessageListViewModel.Recipients] { get set }
    func showLoader()
    func hideLoader()
    func showError(errorMessage: String)
}
